services:
  php:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - app-network
    depends_on:
      - irma
    environment:
      - IRMA_SERVER_URL=http://irma:8088  
      
  irma:
    build: https://github.com/privacybydesign/irmago.git
    ports:
      - "8088:8088"
    command: server --no-auth --no-tls --allow-unsigned-callbacks #--url http://your-network-ip:8088
    networks:
      - app-network

networks:
  app-network:
    driver: bridge